version: '3.8'

services:
  go-server:
    image: golang:latest
    container_name: go-server
    volumes:
      - ./:/go/src/app
    working_dir: /go/src/app
    command: go run main.go
    ports:
      - "8081:8080"
    depends_on:
      - redis-queue
      - redis-pubsub

  redis-queue:
    image: redis:latest
    container_name: redis-queue
    ports:
      - "6378:6379"

  redis-pubsub:
    image: redis:latest
    container_name: redis-pubsub
    ports:
      - "6380:6379"